@baseAddress = http://localhost:5002
@categoryId=08de2448-2130-e207-b025-aa301bbd0000

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###